// Generated by Selenium IDE
const { Builder, By, Key, until,Capabilities, Capability  } = require('selenium-webdriver')
const assert = require('assert')
const firefox = require('selenium-webdriver/firefox');


async function wait (millis) {

	let promise = new Promise((resolve, reject) => {
      setTimeout(() => resolve("Hello World!"), millis)
    });
  
    let result = await promise;
	result = await promise;
	result = await promise;
}

describe('test2', function() {
  this.timeout(90000)
  let driver
  let vars
  //let options
  
  let options = new firefox.Options().setPreference('security.tls.version.min',1);
  //let profile = 'C:/Users/galgano/AppData/Local/Mozilla/Firefox/Profiles/4tnr8mtd.testCTF';
  //options.setProfile(profile);


  

  
  beforeEach(async function() {

	//options = new firefox.Options()
	//	.setProfile( profile ) ;
		
		

    driver = await new Builder().forBrowser('firefox')
		.setFirefoxOptions(options)
		//.withCapabilities(Capabilities.firefox().set("acceptInsecureCerts", true))
		.withCapabilities({'browserName': 'firefox', acceptSslCerts: true, acceptInsecureCerts: true})
		.build()
		
		
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('test2', async function() {
	try{
		res = await driver.get("https://172.21.160.241/eflow/LoginServlet")
	} catch(err) {
		//alert(err)
		console.log(err)
		//await driver.get("https://172.21.160.241/eflow/LoginServlet")
	}
    await driver.manage().window().setRect({ width: 1642, height: 763 })
    await driver.findElement(By.id("txtUID")).sendKeys("20403680")
	await driver.findElement(By.id("txtPsw")).sendKeys("123457")
	
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.id("cmdConferma")).click()
    vars["win5196"] = await waitForWindow(10000)
    vars["root"] = await driver.getWindowHandle()
    await driver.switchTo().window(vars["win5196"])
    await driver.findElement(By.linkText("Working Tasks")).click()
	await wait(5000)
    await driver.switchTo().frame(1)
    await driver.switchTo().frame(1)
    await driver.switchTo().frame(1)
    await driver.switchTo().frame(0)
    await driver.findElement(By.css("td")).click()
    pos = await driver.switchTo().parentFrame()
	console.log(pos)
	await wait(5000)
    await driver.findElement(By.xpath("//img[@title=\'Search Dossier\']")).click()
	await wait(15000)
    await driver.switchTo().parentFrame() //defaultContent
    await driver.switchTo().frame(2)
    await driver.findElement(By.css(".ui-corner-all:nth-child(1) > table > tbody > tr > .Testo:nth-child(2)")).click()
    await driver.findElement(By.id("txtPratNumEsatto")).click()
    await driver.findElement(By.id("txtPratNumEsatto")).sendKeys("867673")
    await driver.findElement(By.id("txtPratNumEsatto")).sendKeys(Key.DOWN)
	await wait(15000)
    await driver.findElement(By.css("form > .ui-corner-all:nth-child(1)")).click()
    await driver.findElement(By.css("#cmdAvvio > .ui-button-text")).click()
    await driver.findElement(By.xpath("(//td[@id=\'cella\'])[4]")).click()
    await driver.findElement(By.xpath("(//td[@id=\'cella\'])[4]")).click()
    await driver.findElement(By.xpath("(//td[@id=\'cella\'])[4]")).click()
    {
      const element = await driver.findElement(By.xpath("(//td[@id=\'cella\'])[4]"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
	await wait(5000)
    await driver.switchTo().frame(0)
    await driver.findElement(By.css("td:nth-child(2)")).click()
    await driver.switchTo().parentFrame()
    await driver.switchTo().frame(1)
    await driver.findElement(By.name("flConfEmp")).click()
    await driver.switchTo().parentFrame()
    await driver.switchTo().frame(0)
    await driver.findElement(By.css("html")).click()
    await driver.switchTo().parentFrame()
    await driver.switchTo().frame(1)
    await driver.findElement(By.name("flConfEmp")).click()
    await driver.findElement(By.name("flConfEmp")).click()
    await driver.findElement(By.css("html")).click()
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css("td:nth-child(1) .sf_char_menu:nth-child(2) img")).click()
    vars["win449"] = await waitForWindow(2000)
    await driver.switchTo().window(vars["win449"])
    await driver.findElement(By.css("html")).click()
    vars["var"] = await driver.findElements(By.xpath("//div[contains(.,\'Warning: flConfEmp must be checked\')]")).length
  })
})
