// Generated by Selenium IDE
const { BootCtf} = require('./bootctf.js');
const { By } = require('selenium-webdriver')
const dossier = process.env.npm_config_dossier;
const username = process.env.npm_config_username;
const password = process.env.npm_config_password;

describe('test3', function () {
  this.timeout(900000)
  let driver
  let vars

  beforeEach(async function () {
    vars = {}
    driver = await BootCtf.create()
  })

  afterEach(async function () {
    await driver.quit();
  })

  it('test3', async function () {

    await BootCtf.login(driver, vars, username, password)

    await BootCtf.openDetailsDossier(driver, vars, dossier) 

    flConfEmp = await driver.findElement(By.name("flConfEmp"))
    flConfEmp.click()

    await driver.sleep(2000)
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css("td:nth-child(1) .sf_char_menu:nth-child(2) img")).click()
    vars["W_FLCONFEMP_CHECK"] = await BootCtf.waitForWindow(driver, vars, 2000)
    await driver.switchTo().window(vars["W_FLCONFEMP_CHECK"])
    html = await driver.findElement(By.css("html"))//.click()
    txt = await html.getText()
    console.log("html txt", txt)
    html.click()
    vars["var"] = await driver.findElements(By.xpath("//div[contains(.,'Warning: flConfEmp must be checked')]")).length
    console.log("ESITO", (txt === 'Warning: flConfEmp must be checked'))

  })
})
