// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('testj1', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('testj1', async function() {
    await driver.get("http://joomla-cms.loc/")
    await driver.manage().window().setRect({ width: 1464, height: 846 })
	await driver.wait(until.elementLocated(By.id(`modlgn-username-16`)), 5000);
    await driver.findElement(By.id("modlgn-username-16")).click()
    await driver.findElement(By.id("modlgn-passwd-16")).sendKeys("admin1234567890")
    await driver.findElement(By.id("modlgn-username-16")).sendKeys("admin")
    await driver.findElement(By.name("Submit")).click()
    await driver.findElement(By.css(".item-content:nth-child(1) > .icons a")).click()
    await driver.findElement(By.id("jform_title")).click()
    await driver.findElement(By.id("jform_title")).sendKeys("Welcome to your blogX")
    await driver.findElement(By.css(".mb-2 > .btn:nth-child(1)")).click()
    await driver.findElement(By.name("Submit")).click()
  })
})
