// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('test2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('test2', async function() {
    await driver.get("https://172.21.160.241/eflow/LoginServlet")
    await driver.get("https://172.21.160.241/eflow/LoginServlet")
    await driver.manage().window().setRect({ width: 1642, height: 763 })
    await driver.findElement(By.id("txtUID")).sendKeys("20403680")
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.id("cmdConferma")).click()
    vars["win5196"] = await waitForWindow(2000)
    vars["root"] = await driver.getWindowHandle()
    await driver.switchTo().window(vars["win5196"])
    await driver.findElement(By.linkText("Working Tasks")).click()
    await driver.switchTo().frame(1)
    await driver.switchTo().frame(1)
    pos = await driver.switchTo().frame(1)
	console.log("qui#########")
	console.log(pos)
    await driver.switchTo().frame(0)
    await driver.findElement(By.css("td")).click()
    await driver.switchTo().parentFrame()
    await driver.findElement(By.xpath("//img[@title=\'Search Dossier\']")).click()
    await driver.switchTo().defaultContent()
    await driver.switchTo().frame(2)
    await driver.findElement(By.css(".ui-corner-all:nth-child(1) > table > tbody > tr > .Testo:nth-child(2)")).click()
    await driver.findElement(By.id("txtPratNumEsatto")).click()
    await driver.findElement(By.id("txtPratNumEsatto")).sendKeys("867673")
    await driver.findElement(By.id("txtPratNumEsatto")).sendKeys(Key.DOWN)
    await driver.findElement(By.css("form > .ui-corner-all:nth-child(1)")).click()
    await driver.findElement(By.css("#cmdAvvio > .ui-button-text")).click()
    await driver.findElement(By.xpath("(//td[@id=\'cella\'])[4]")).click()
    await driver.findElement(By.xpath("(//td[@id=\'cella\'])[4]")).click()
    await driver.findElement(By.xpath("(//td[@id=\'cella\'])[4]")).click()
    {
      const element = await driver.findElement(By.xpath("(//td[@id=\'cella\'])[4]"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.switchTo().frame(0)
    await driver.findElement(By.css("td:nth-child(2)")).click()
    await driver.switchTo().defaultContent()
    await driver.switchTo().frame(1)
    await driver.findElement(By.name("flConfEmp")).click()
    await driver.switchTo().defaultContent()
    await driver.switchTo().frame(0)
    await driver.findElement(By.css("html")).click()
    await driver.switchTo().defaultContent()
    await driver.switchTo().frame(1)
    await driver.findElement(By.name("flConfEmp")).click()
    await driver.findElement(By.name("flConfEmp")).click()
    await driver.findElement(By.css("html")).click()
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css("td:nth-child(1) .sf_char_menu:nth-child(2) img")).click()
    vars["win449"] = await waitForWindow(2000)
    await driver.switchTo().window(vars["win449"])
    await driver.findElement(By.css("html")).click()
    vars["var"] = await driver.findElements(By.xpath("//div[contains(.,\'Warning: flConfEmp must be checked\')]")).length
  })
})
