// Generated by Selenium IDE

const { BootCtf} = require('./bootctf.js');

//const {MyClass1} = require('./test.js')
const { By } = require('selenium-webdriver')
const dossier = process.env.npm_config_dossier;
const username = process.env.npm_config_username;
const password = process.env.npm_config_password;
console.log("dossier", dossier)
console.log("username", username)
console.log("password", password)

async function wait(millis) {
  let promise = new Promise((resolve, reject) => {
    setTimeout(() => resolve("Hello World!"), millis)
  });
  let result = await promise;
}

describe('test3', function () {
  this.timeout(900000)
  let driver
  let vars

  beforeEach(async function () {
    vars = {}
    driver = await BootCtf.create()
  })

  afterEach(async function () {
    await driver.quit();
  })

  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }

  it('test3', async function () {

    await BootCtf.login(driver, vars, username, password)
    
    await BootCtf.openDossier(driver, vars, dossier)

    await driver.switchTo().defaultContent()


    frBody = await driver.findElement(By.id("frBody"));
    driver.switchTo().frame(frBody);

    elem = await driver.findElements(By.tagName("iframe"))


    elem2 = await driver.findElements(By.tagName("frame"))

    driver.switchTo().frame(1); // frame id = frMain

    driver.switchTo().frame(2) // frame name = MainForm

    driver.switchTo().frame(0) // frame id = Lista

    console.log("inner ctf dom")
    await driver.sleep(13000)

    elemchild = await driver.findElement(By.css("td:nth-child(2)"))//.click()
    elemchild.click()

    await driver.sleep(3000)


    driver.switchTo().parentFrame()

    await wait(2000)

    driver.switchTo().frame(1); // frame name = BODY
    await wait(2000)
    flConfEmp = await driver.findElement(By.name("flConfEmp"))

    flConfEmp.click()

    await wait(2000)
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css("td:nth-child(1) .sf_char_menu:nth-child(2) img")).click()
    vars["win7729"] = await waitForWindow(2000)
    await driver.switchTo().window(vars["win7729"])
    await wait(2000)
    html = await driver.findElement(By.css("html"))//.click()
    txt = await html.getText()
    console.log("html txt", txt)
    html.click()
    vars["var"] = await driver.findElements(By.xpath("//div[contains(.,'Warning: flConfEmp must be checked')]")).length
    console.log("POPUP", (txt === 'Warning: flConfEmp must be checked'))
    await wait(5000)
  })
})
